package com.ats.model;

import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;

@Getter
@Setter
public class BookingDTO {
    private String id;  // This will be autogenerated
    private String passengerName;
    private LocalDate bookingDate;
    private int seatNumber;
    private int ticketCost;
    private int totalAmount;
    private String departureDate;
    private String departureTime;
    private String arrivalDate;
    private String arrivalTime;
}
